name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration:
    strategy:
      matrix:
        node-version: [14.16.1]
    runs-on: ubuntu-latest

    steps:
      - name: ğŸšš Git Checkout
        uses: actions/checkout@v2

      - name: âš™ï¸ Set Up Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ”§ Install Yarn
        run: npm install -g yarn

      - name: ğŸ”¨ Install Packages
        run: yarn

      - name: ğŸ‘ŒğŸ½ Lint
        run: yarn lint

      - name: ğŸ›  Build
        run: yarn build
